config/routes.rb
Rails.application.routes.draw do
  get 'locations/index'
  scope '/api' do
    resources :degrees, only: [:index] do
      resources :programmes, only: [:index]
    end
    resources :programmes, only: [:index]
    get 'contract_types' => "contract_types#index"
    get 'locations' => "locations#index"
  end

  resources :market_favorites
  get 'blat' => 'blat#index', as: 'blat'

  resources :applications, only: [:create, :show, :destroy]

  scope '/admin' do
    resources :job_offers, path: 'ofertas', except: [:new] do
      member do
        patch 'send_applications' => 'job_offers#send_applications', as: :send_applications
        patch 'trash' => 'job_offers#trash', as: :trash
        patch 'restore' => 'job_offers#restore', as: :restore
        patch 'approve' => 'job_offers#approve', as: :approve
      end
    end
    resources :settings
    resources :site_assets
    resources :markets, path: 'feira', except: [:show, :update, :destroy]
    resources :degrees, path: 'graus'
    resources :programmes, path: 'cursos'
    get 'empresas/qr' => "companies#qr_codes", as: :companies_qr
    resources :companies, path: 'empresas', except: [:show, :update, :destroy] do
      collection do
        get 'new/:nif' => 'companies#nif_lookup', as: :nif_lookup
      end
    end
  end
  resources :companies, path: 'empresa', only: [:show, :update, :destroy]
  resources :markets, param: :market_id, path: 'feira', only: [:show, :update, :destroy] do
    member do
      get 'empresa/:id' => 'companies#show', as: :company
    end
  end
  resources :job_offers, path: '/oferta', only: [:new] do
    collection do
      get 'estudantes/:random_id' => 'job_offers#students', as: :students
    end
  end

  # devise_for :users
  get 'users/codes' => "users#random_index"
  devise_for :users, path: '', path_names: { sign_in: 'entrar', sign_out: 'sair'}
  resources :users do
    collection do
      resources :profiles
    end
  end
  match 'admin' => 'degrees#index', via: :get

  patch 'toggle_review/:id' => 'profiles#toggle_review', as: :profile_review
  patch 'profiles/:id/incomplete' => 'profiles#incomplete_profile', as: :incomplete_profile
  delete 'delete_curriculum/:id' => 'profiles#delete_curriculum', as: :delete_curriculum

  match 'perfil' => 'profiles#show', as: :my_profile, via: :get
  match 'perfil/editar' => 'profiles#edit', as: :edit_my_profile, via: :get
  match 'utilizador' => 'users#show', as: :my, via: :get
  get 'utilizador/qr' => 'users#qr_code', as: :my_qr

  get 'feira' => 'pages#market', as: :market_page
  scope 'feira', as: 'market' do
    resources :companies, only: [:show], path: :empresa do
      member do
        get 'qr' => "companies#company_qr", as: :qr
      end
    end
  end
  root 'pages#index'
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :confirmable, :recoverable, :rememberable, :trackable,
         :validatable, :invitable

  before_create :generate_random_string
  after_create :assign_default_role

  has_one :profile, dependent: :destroy
  has_many :applications, dependent: :destroy
  has_many :views, foreign_key: :user_id, class_name: "JobView", dependent: :destroy

  has_many :market_favorites, through: :profile

  has_and_belongs_to_many :companies, limit: 1

  accepts_nested_attributes_for :applications

  def generate_random_string
    while(!User.find_by(random_string: (self.random_string = SecureRandom.hex(3))).blank?)
    end
  end

  def self.generate_random_strings
    User.all.each do |user|
      user.generate_random_string
      user.save
    end
  end

  def self.filter query, filter
    case filter
    when 'approved'
      return query.where("profiles.complete": true, "profiles.reviewed": true)
    when 'approve'
      return query.where("profiles.complete": true, "profiles.reviewed": false)
    when 'incomplete'
      return query.where("profiles.complete": false)
    else
      return query
    end
  end

  def assign_default_role
    self.add_role :newuser if self.roles.blank?
  end

  def assign_role new_role
    self.remove_role :newuser
    self.add_role new_role
  end

  def complete?
    if self.has_role? :student
      return self.profile.complete?
    else
      return true
    end
  end

  def incomplete?
    !self.complete?
  end

  def make_student
    self.assign_role :student
  end

  def name
    if self.profile.blank?
      return self.email
    else
      return self.profile.name
    end
  end

  def create_view job_offer
    if self.has_role? :student
      JobView.create_later(self, job_offer)
    end
  end

  def profile_qr
    require 'rqrcode'
    RQRCode::QRCode.new( Rails.application.routes.url_helpers.user_url(self) )
  end

  def to_param
    self.random_string
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource except: [:show, :random_index, :qr_code]
  before_action :set_user, only: [:show, :update, :destroy, :qr_code]

  def qr_code
    data = @user.profile_qr.as_png(size: 512, border_modules: 4).to_s
    send_data data, type: 'image/png', filename: 'qr.png'
  end

  def random_index
    authorize! :manage, User
    @users = User.without_role(:blat).order(:random_string)
  end

  def index
    if current_user.has_role? :blat
      @role = 'all'
      @users = User.all.order(:email)
      render layout: 'admin'
    else
      params[:role] ||= 'student'
      @filter = params[:filter] ||= 'all'
      @role = params[:role]
      @order = params[:order] || "email"
      case @order
      when "email"
        @order = "users.email"
      when "name"
        @order = "profiles.name"
      when "reviewed"
        @order = "profiles.reviewed"
      else
        @order = ""
      end
      puts @order

      if @role == 'student'
        @users = User.with_role(@role).joins(:profile).order(@order, "profiles.name")
      else
        @users = User.with_role(@role).order(@order)
      end

      @users = User.filter(@users, @filter)

      render layout: 'admin'
    end
  end

  def show
    authorize! :show, @user

    if current_user.has_role? :recruiter
      @company = current_user.companies.first
      @market = Market.find_by(active: true)
      @favorite = @user.profile.market_favorites.new(market: @market, company: @company)
      @favorite.save
      notice = "Registadas as informações de #{@user.name}"
      redirect_to @company, notice: notice
    end

    unless @user.profile.blank?
      @profile = @user.profile
    end

    if can? :manage, User
      render :admin_show, layout: 'admin'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to job_offers_path, notice: 'User atualizado'
    else
      redirect_to job_offers_path, notice: 'Erro a atualizar utilizador'
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path, notice: 'Utilizador "' + @user.name + '" eliminado' }
      format.json { head :no_content }
    end
  end

  private
    def user_params
      params.require(:user).permit(application: [:user_id, :job_offer_id])
    end

    def set_user
      if params[:id].blank?
        @user = current_user
      else
        @user = User.find_by random_string: params[:id]
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/admin_show.html.erb
<div class="menu">
  <% if @user.has_role? :admin %>
    <%= link_to fa_icon('level-up lg fw', text: 'Administradores'), users_path(role: 'admin') %>
  <% elsif @user.has_role? :student %>
    <%= link_to fa_icon('level-up lg fw', text: 'Estudantes'), User %>
  <% else %>
    <%= link_to fa_icon('level-up lg fw', text: 'Utilizadores'), User %>
  <% end %>
</div>

<div id="user">
  <h2>
    <%= title @user.name %>
    <small>
      <%= link_to 'Eliminar', @user, method: :delete, class: 'alert', data: { confirm: 'Tem a certeza?' } %>
    </small>
  </h2>

  <%= content_tag(:div, @user.profile_qr.as_svg(class: 'sdsds').html_safe, class: 'user-qr') %>

  <% if @user.has_role? :student %>
    <% if !@user.profile.blank? %>

      <div class="profile-details">
        <span><strong>Telefone:</strong> <%= @user.profile.phone %></span>
        <span><strong>Curso:</strong> [<%= @user.profile.degree %>] <%= @user.profile.programme.name %></span>
        <span><% link_to fa_icon('pencil fw', text: 'Alterar dados pessoais'), edit_user_path(@user) %></span>
      </div>
    <% end %>

    <% unless @user.profile.curriculum.blank? %>
      <object data="<%= @user.profile.curriculum.url %>" type="application/pdf" width="100%" height="800px">
         <p><b>Example fallback content</b>: This browser does not support PDFs. Please download the PDF to view it: <a href="/pdf/sample-3pp.pdf">Download PDF</a>.</p>
      </object>

      <div class="menu">
        <%= link_to fa_icon('trash lg', text: 'Eliminar Curriculum'), delete_curriculum_path(@user.profile), method: :delete, class: 'button alert', data: { confirm: 'Tem a certeza?' } %>
      </div>
    <% end %>

    <div class="menu">
      <%= button_to profile_review_path(@user.profile), class: "button #{'success' if @user.profile.reviewed}", method: :patch do %>
        <div class="<%= 'hide' if @user.profile.reviewed %>">
          <%= fa_icon('check lg') %> Aprovar Perfil
        </div>
        <div class="<%= 'hide' unless @user.profile.reviewed %>">
          <%= fa_icon('times lg') %> Marcar para revisão
        </div>
      <% end %>
      <% if @user.complete? %>
        <%= button_to incomplete_profile_path(@user.profile), class: "button #{'success' if @user.profile.reviewed}", method: :patch do %>
          <div>
            <%= fa_icon('times lg') %> Marcar como incompleto
          </div>
        <% end %>
      <% end %>
    </div>

  <% end %>
</div>

app/views/users/index.html.erb
<div class="menu">
  <%= active_link_to fa_icon('graduation-cap lg fw', text: 'Estudantes'), User, active: @role == 'student' %>
  <%= active_link_to fa_icon('user lg fw', text: 'Administradores'), users_path(role: :admin), active: {role: :admin} %>
</div>

<h1><%= title 'Utilizadores' %></h1>

<% if @role == 'student' %>
  <div class="filters">
    <%= active_link_to 'Todos', User, active: @filter == 'all' %>
    <%= active_link_to 'Aprovados', users_path(filter: :approved, order: params[:order]), active: {filter: :approved} %>
    <%= active_link_to 'Por Aprovar', users_path(filter: :approve, order: params[:order]), active: {filter: :approve} %>
    <%= active_link_to 'Incompletos', users_path(filter: :incomplete, order: params[:order]), active: {filter: :incomplete} %>
  </div>
<% end %>

<table>
  <thead>
    <tr>
      <% if @role == 'student' %>
        <th><%= link_to "Revisto", users_path(order: 'reviewed', role: params[:role], filter: params[:filter]) %></th>
        <th><%= link_to "Nome", users_path(order: 'name', role: params[:role], filter: params[:filter]) %></th>
      <% end %>
      <th><%= link_to "Email", users_path(order: 'email', role: params[:role], filter: params[:filter]) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
        <tr<%= " class=alert" if user.incomplete? %>>
        <% if @role == 'student' %>
          <td class="text-center">
            <%=  user.profile.reviewed ? fa_icon("check 2x") : fa_icon("times 2x") %>
          </td>
          <td><%= user.name %></td>
        <% end %>
        <td><%= link_to user.email, user %></td>
        <td class='text-center'><%= link_to fa_icon('trash 2x'), user, method: :delete, class: 'alert', data: { confirm: 'Tem a certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/random_index.html.erb
<h1><%= title 'Códigos' %></h1>

<table>
  <thead>
    <tr>
      <th>Código</th>
      <th>Nome</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.random_string %></td>
        <td><%= user.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<% title @user.name %>

<div class="col" id="user-profile">
  <% if can? :manage, User %>
    <%= link_to 'Perfil', profile_path(@user.profile) unless @user.profile.blank? %>
  <% else can? :manage, @user %>
    <% if !@profile.blank? %>
      <h2><%= @profile.name %></h2>

      <%= content_tag(:div, @user.profile_qr.as_svg(class: 'sdsds').html_safe, class: 'user-qr') %>
      
      <% if can? :manage, @user %>
        <%= link_to 'Transferir QR', my_qr_path, target: :_blank, class: 'text-center' %>

        <h4>Código: <%= @profile.user.random_string %></h4>

        <h5>Curriculum Vitae</h5>
        <div id="curriculum-upload">
          <%= link_to fa_icon('file-pdf-o 5x'), @profile.curriculum.url, target: '_blank', id: 'curriculum-url', class: @profile.curriculum? ? '' : 'missing' %>

          <%= form_for @profile, html: {id: 'curriculum-upload-form'} do |f| %>
            <span class='button' id="curriculum-upload-button">Upload</br>(Arrastar ficheiro para aqui)</span>
          <% end %>

          <%= form_for @profile do |f| %>
            <%= f.hidden_field :curriculum, value: nil %>
            <% if @profile.curriculum? %>
              <%= f.button fa_icon('trash 3x'), class: 'curriculum-destroy alert button' %>
            <% else %>
              <%= f.button fa_icon('trash 3x'), class: 'curriculum-destroy alert button hidden' %>
            <% end %>
          <% end %>
        </div>

        <div class="profile-details">
          <h5>Dados de <%= @profile.name %></h5>
          <span><strong>Telefone:</strong> <%= @profile.phone %></span>
          <span><strong>Curso:</strong> [<%= @profile.degree %>] <%= @profile.programme.name %></span>
          <span><%= link_to fa_icon('pencil fw', text: 'Alterar dados pessoais'), edit_my_profile_path %></span>
        </div>
      <% end %>
    <% end %>

    <% if can? :manage, @user %>
      <span><%= link_to fa_icon('lock fw', text: 'Alterar dados de acesso'), edit_registration_path(current_user) %></span>
      <span><%= link_to fa_icon('sign-out fw', text: 'Sair'), destroy_user_session_path, method: :delete, class: 'alert' %></span>
    <% end %>
  <% end %>
</div>