config/routes.rb
Rails.application.routes.draw do
  get 'locations/index'
  scope '/api' do
    resources :degrees, only: [:index] do
      resources :programmes, only: [:index]
    end
    resources :programmes, only: [:index]
    get 'contract_types' => "contract_types#index"
    get 'locations' => "locations#index"
  end

  resources :market_favorites
  get 'blat' => 'blat#index', as: 'blat'

  resources :applications, only: [:create, :show, :destroy]

  scope '/admin' do
    resources :job_offers, path: 'ofertas', except: [:new] do
      member do
        patch 'send_applications' => 'job_offers#send_applications', as: :send_applications
        patch 'trash' => 'job_offers#trash', as: :trash
        patch 'restore' => 'job_offers#restore', as: :restore
        patch 'approve' => 'job_offers#approve', as: :approve
      end
    end
    resources :settings
    resources :site_assets
    resources :markets, path: 'feira', except: [:show, :update, :destroy]
    resources :degrees, path: 'graus'
    resources :programmes, path: 'cursos'
    get 'empresas/qr' => "companies#qr_codes", as: :companies_qr
    resources :companies, path: 'empresas', except: [:show, :update, :destroy] do
      collection do
        get 'new/:nif' => 'companies#nif_lookup', as: :nif_lookup
      end
    end
  end
  resources :companies, path: 'empresa', only: [:show, :update, :destroy]
  resources :markets, param: :market_id, path: 'feira', only: [:show, :update, :destroy] do
    member do
      get 'empresa/:id' => 'companies#show', as: :company
    end
  end
  resources :job_offers, path: '/oferta', only: [:new] do
    collection do
      get 'estudantes/:random_id' => 'job_offers#students', as: :students
    end
  end

  # devise_for :users
  get 'users/codes' => "users#random_index"
  devise_for :users, path: '', path_names: { sign_in: 'entrar', sign_out: 'sair'}
  resources :users do
    collection do
      resources :profiles
    end
  end
  match 'admin' => 'degrees#index', via: :get

  patch 'toggle_review/:id' => 'profiles#toggle_review', as: :profile_review
  patch 'profiles/:id/incomplete' => 'profiles#incomplete_profile', as: :incomplete_profile
  delete 'delete_curriculum/:id' => 'profiles#delete_curriculum', as: :delete_curriculum

  match 'perfil' => 'profiles#show', as: :my_profile, via: :get
  match 'perfil/editar' => 'profiles#edit', as: :edit_my_profile, via: :get
  match 'utilizador' => 'users#show', as: :my, via: :get
  get 'utilizador/qr' => 'users#qr_code', as: :my_qr

  get 'feira' => 'pages#market', as: :market_page
  scope 'feira', as: 'market' do
    resources :companies, only: [:show], path: :empresa do
      member do
        get 'qr' => "companies#company_qr", as: :qr
      end
    end
  end
  root 'pages#index'
end

app/models/setting.rb
class Setting < ApplicationRecord
  validates :name, uniqueness: true
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  load_and_authorize_resource
  before_action :set_setting, only: [:show, :edit, :update, :destroy]
  layout 'admin'

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:name, :value)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_with(model: setting, local: true) do |form| %>
  <% if setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :setting_name %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :setting_value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<h1>Settings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.name %></td>
        <td><%= setting.value %></td>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @setting.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @setting.value %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>