config/routes.rb
Rails.application.routes.draw do
  get 'locations/index'
  scope '/api' do
    resources :degrees, only: [:index] do
      resources :programmes, only: [:index]
    end
    resources :programmes, only: [:index]
    get 'contract_types' => "contract_types#index"
    get 'locations' => "locations#index"
  end

  resources :market_favorites
  get 'blat' => 'blat#index', as: 'blat'

  resources :applications, only: [:create, :show, :destroy]

  scope '/admin' do
    resources :job_offers, path: 'ofertas', except: [:new] do
      member do
        patch 'send_applications' => 'job_offers#send_applications', as: :send_applications
        patch 'trash' => 'job_offers#trash', as: :trash
        patch 'restore' => 'job_offers#restore', as: :restore
        patch 'approve' => 'job_offers#approve', as: :approve
      end
    end
    resources :settings
    resources :site_assets
    resources :markets, path: 'feira', except: [:show, :update, :destroy]
    resources :degrees, path: 'graus'
    resources :programmes, path: 'cursos'
    get 'empresas/qr' => "companies#qr_codes", as: :companies_qr
    resources :companies, path: 'empresas', except: [:show, :update, :destroy] do
      collection do
        get 'new/:nif' => 'companies#nif_lookup', as: :nif_lookup
      end
    end
  end
  resources :companies, path: 'empresa', only: [:show, :update, :destroy]
  resources :markets, param: :market_id, path: 'feira', only: [:show, :update, :destroy] do
    member do
      get 'empresa/:id' => 'companies#show', as: :company
    end
  end
  resources :job_offers, path: '/oferta', only: [:new] do
    collection do
      get 'estudantes/:random_id' => 'job_offers#students', as: :students
    end
  end

  # devise_for :users
  get 'users/codes' => "users#random_index"
  devise_for :users, path: '', path_names: { sign_in: 'entrar', sign_out: 'sair'}
  resources :users do
    collection do
      resources :profiles
    end
  end
  match 'admin' => 'degrees#index', via: :get

  patch 'toggle_review/:id' => 'profiles#toggle_review', as: :profile_review
  patch 'profiles/:id/incomplete' => 'profiles#incomplete_profile', as: :incomplete_profile
  delete 'delete_curriculum/:id' => 'profiles#delete_curriculum', as: :delete_curriculum

  match 'perfil' => 'profiles#show', as: :my_profile, via: :get
  match 'perfil/editar' => 'profiles#edit', as: :edit_my_profile, via: :get
  match 'utilizador' => 'users#show', as: :my, via: :get
  get 'utilizador/qr' => 'users#qr_code', as: :my_qr

  get 'feira' => 'pages#market', as: :market_page
  scope 'feira', as: 'market' do
    resources :companies, only: [:show], path: :empresa do
      member do
        get 'qr' => "companies#company_qr", as: :qr
      end
    end
  end
  root 'pages#index'
end

app/models/company.rb
class Company < ApplicationRecord
    has_and_belongs_to_many :users
    has_and_belongs_to_many :markets
    has_and_belongs_to_many :profiles # this is placeholder for student view of companies
    has_many :market_favorites, dependent: :destroy

    has_attached_file :logo, styles: { medium: "175x175>", thumb: "100x100>" }, default_url: Setting.find_by(name: 'Logo Top').value
    validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
    validates :nif, uniqueness: true, allow_nil: true

    before_save :fix_website

    def profile_qr market_id = nil
        require 'rqrcode'
        if market_id
            path = Rails.application.routes.url_helpers.company_market_url(market_id, self, apply: true) 
        else
            path = Rails.application.routes.url_helpers.market_company_url(self, apply: true) 
        end
        RQRCode::QRCode.new path
    end

    def nif_check attribute
        if attribute === :name
            json_attribute = 'title'
        else
            json_attribute = attribute.to_s
        end
        self[attribute] === self.nif_json[json_attribute]
    end

    def nif_update
        if self.nif != nil && Company.can_search_nif?
            url = "http://www.nif.pt/?json=1&q=#{self.nif}&key=#{ENV['NIF_KEY']}"
            json = JSON.parse(Net::HTTP.get(URI.parse(url)))
            puts json
            if json['result'] === "success"
                company_json = json["records"][nif.to_s]
                self.name = company_json["title"] if self.name.blank?
                #self.address = company_json["address"] if self.address.blank?
                self.city = company_json["city"] if self.city.blank?
                self.description = company_json["activity"] if self.description.blank?
                self.nif_json = company_json
                self.nif_checked_at = DateTime.now
            end
            self.save
        end
    end

    def self.find_and_update_missing_info
        c = Company.where(nif_checked_at: nil).where.not(nif: nil).first
        c.nif_update unless c.blank?
    end

    def self.can_search_nif?
        url = "http://www.nif.pt/?json=1&credits=1&key=#{ENV['NIF_KEY']}"
        credits = JSON.parse(Net::HTTP.get(URI.parse(url)))['credits']
        puts credits
        credits['minute'] > 0
    end

    def self.new_by_nif nif
        company = Company.new
        if Company.can_search_nif?
            url = "http://www.nif.pt/?json=1&q=#{nif}&key=#{ENV['NIF_KEY']}"
            json = JSON.parse(Net::HTTP.get(URI.parse(url)))
            puts json
            if json['result'] === "success"
                company_json = json["records"][nif.to_s]
                company.name = company_json["title"]
                #company.address = company_json["address"]
                company.city = company_json["city"]
                company.description = company_json["activity"]
            end
        end
        company
    end

    def fix_website
        if !self.website.blank? and !self.website.start_with?('http')
            self.website = 'http://' + self.website
        end
    end

    def create_user
        unless self.email.blank?
            user = self.users.new email: self.email
            user.add_role :recruiter
            user.password = "jobshop@2018"
            user.skip_confirmation!
            user.save
            user.companies << self
        end
        user
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_company, only: [:show, :edit, :update, :destroy, :company_qr]
  layout 'admin', except: [:show]

  def company_qr
    data = @company.profile_qr.as_png(size: 512, border_modules: 4).to_s
    send_data data, type: 'image/png', filename: 'qr.png'
  end

  def qr_codes
    @companies = Company.all.order(:name)
  end

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all.order(:name)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    if( params[:market_id] )
      @market = Market.find params[:market_id]
    else
      @market = @company.markets.find_by(active: true)
    end
    authorize! :read, @market
    if current_user.has_role? :recruiter and current_user.valid_password? 'jobshop@2018'
      redirect_to edit_registration_path(current_user)
    else

      unless current_user.profile.blank?
        unless current_user.profile.companies.exists? @company.id
          current_user.profile.companies << @company
          @company.views = @company.profiles.count
          @company.save
        end
      end

      if( params[:apply] === 'true' )
        @favorite = current_user.profile.market_favorites.new(market: @market, company: @company)
        begin
          @favorite.save
          flash.now[:notice] = 'Informações submetidas com sucesso!'
        rescue ActiveRecord::RecordNotUnique
          flash.now[:notice] = 'Já submeteste informações à ' + @company.name
        end
      end
      render layout: 'markets'
    end
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to Company, notice: "Empresa '#{@company.name}' criada" }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to edit_company_path(@company), notice: "Empresa '#{@company.name}' atualizada" }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Empresa '#{@company.name}' eliminada" }
      format.json { head :no_content }
    end
  end

  def nif_lookup
    render json: Company.new_by_nif(params[:nif])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :country, :city, :description, :nif, :logo, :website, :email)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<%= link_to market_company_path(company), class: 'job-link', data: {id: company.id } do %>
  <div class="card job-offer">
    <div class="job-image">
      <%= image_tag company.logo.url(:medium) %>
    </div>

    <div class="content">
      <h3><%= company.name %></h3>
    </div>

    <div class='engagement'>
      <div class="stats">
        <%= fa_icon 'eye fw', text: company.profiles.count %>
      </div>

      <%-# if application.blank? %>
      <% if mh_is_company_favorite? @market, company %>
        <div class="job-remove-application">
          Remover CV
        </div>
      <% else %>
        <div class="job-add-application">
          Enviar CV
        </div>
      <% end %>
    </div>
  </div>
<% end %>
<% if mh_is_company_favorite? @market, company %>
  <%= link_to(
    'Remover',
    mh_company_favorite(@market, company),
    class: 'button alert hide',
    method: :delete,
    id: "application#{company.id}",
    data: { confirm: 'Tem a certeza?' }
  )%>
<% end %>

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true, html: {id: 'company-form-logo'}) do |form| %>
  <%= form.file_field :logo %>
  <%= image_tag(company.logo.url(:medium), id: 'company-logo') %>
<% end %>

<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(company.errors.count, "erro") %></h4>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <% if company.nif_json %>
      <span><strong>nif.pt:</strong> <%= company.nif_json['title'] %></span>
    <% end %>
    <%= form.text_field :name, id: 'name' %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <% if company.nif_json %>
      <span><strong>nif.pt:</strong> <%= company.nif_json['contacts']['website'] %></span>
    <% end %>
    <%= form.text_field :website, id: 'website', rows: 4 %>
  </div>

  <div class="field">
    <%= form.label :nif, 'NIF' %>
    <% if company.nif_json %>
      <span><strong>nif.pt:</strong> <%= company.nif_json['nif'] %></span>
    <% end %>
    <%= form.text_field :nif, id: 'nif' %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: 'country' %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <% if company.nif_json %>
      <span><strong>nif.pt:</strong> <%= company.nif_json['city'] %></span>
    <% end %>
    <%= form.text_field :city, id: 'city' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <% if company.nif_json %>
      <span><strong>nif.pt:</strong> <%= company.nif_json['activity'] %></span>
    <% end %>
    <%= form.text_area :description, id: 'description', rows: 4 %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, id: 'email' %>
  </div>

  <div class="actions">
    <%= form.button 'Gravar', class: 'button expanded' %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div id="admin-page-menu">
    <%= link_to fa_icon('chevron-up 2x fw'), companies_path, class: 'button' %>
    <h1><%= title @company.name %></h1>
    <%= link_to fa_icon('plus 2x fw'), new_company_path, class: 'button' %>
</div>

<%= render 'form', company: @company %>

app/views/companies/index.html.erb
<div id="admin-page-menu">
  <h1><%= title 'Empresas' %></h1>
  <%= link_to fa_icon('qrcode lg fw'), companies_qr_path, class: 'button' %>
  <%= link_to fa_icon('plus lg fw'), new_company_path, class: 'button' %>
</div>

<table>
  <thead>
    <tr>
      <th><%= t 'attributes.name' %></th>
      <th><%= t 'attributes.city' %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.name, edit_company_path(company) %></td>
        <td><%= company.city %></td>
        <td><%= link_to fa_icon('trash 2x fw'), company, method: :delete, data: { confirm: 'Are you sure?' }, class: 'alert' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/new.html.erb
<div id="admin-page-menu">
    <%= link_to fa_icon('chevron-up 2x fw'), companies_path, class: 'button' %>
    <h1><%= title "Adicionar Empresa" %></h1>
</div>


<%= render 'form', company: @company %>

app/views/companies/qr_codes.html.erb
<div id="admin-page-menu">
  <h1><%= title 'Empresas' %></h1>
  <%= link_to fa_icon('list lg fw'), companies_path, class: 'button' %>
  <%= link_to fa_icon('plus lg fw'), new_company_path, class: 'button' %>
</div>

<% @companies.each do |company| %>
  <div class="text-center">
    <h3><%= company.name %></h3>
    <p>
      <%= company.profile_qr(params[:market_id]).as_svg().html_safe %>
    </p>
  </div>
<% end %>

app/views/companies/show.html.erb
<div class="admin-content">
  <div id="company">
    <div id="company-images">
      <%= image_tag(@company.logo.url) %>
      <%= @company.profile_qr(params[:market_id]).as_svg().html_safe %>
    </div>
    <h1><%= title @company.name %></h1>

    <p><strong>Pais:</strong> <span><%= @company.country %></span></p>
    <p><strong>Cidade:</strong> <span><%= @company.city %></span></p>
    <p><strong>Web:</strong> <a href="<%= @company.website %>" target="_blank"><%= @company.website %></a></p>
    <div><div><%= simple_format @company.description %></div></div>

    <% if current_user.has_role? :recruiter or can? :manage, @company %>
      <p><strong>Alunos interessados:</strong> <%= @company.market_favorites.count %></p>

      <% @company.market_favorites.each do |student| %>
        <div class="job-offer-student">
          <%= link_to(
            student.profile.curriculum.url,
            target: '_blank',
            download: true,
            data: {filename: "#{student.profile.programme.full_name} - #{student.profile.name}.pdf"}
          ) do %>
            <div class="job-offer-student-name">
              <%= student.profile.name %>
            </div>
            <div class="job-offer-student-programme">
              <%= student.profile.programme.full_name %>
            </div>
            <div class="job-offer-student-icon">
              <%= fa_icon('download') %>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
    
  </div>
</div>