config/routes.rb
Rails.application.routes.draw do
  get 'locations/index'
  scope '/api' do
    resources :degrees, only: [:index] do
      resources :programmes, only: [:index]
    end
    resources :programmes, only: [:index]
    get 'contract_types' => "contract_types#index"
    get 'locations' => "locations#index"
  end

  resources :market_favorites
  get 'blat' => 'blat#index', as: 'blat'

  resources :applications, only: [:create, :show, :destroy]

  scope '/admin' do
    resources :job_offers, path: 'ofertas', except: [:new] do
      member do
        patch 'send_applications' => 'job_offers#send_applications', as: :send_applications
        patch 'trash' => 'job_offers#trash', as: :trash
        patch 'restore' => 'job_offers#restore', as: :restore
        patch 'approve' => 'job_offers#approve', as: :approve
      end
    end
    resources :settings
    resources :site_assets
    resources :markets, path: 'feira', except: [:show, :update, :destroy]
    resources :degrees, path: 'graus'
    resources :programmes, path: 'cursos'
    get 'empresas/qr' => "companies#qr_codes", as: :companies_qr
    resources :companies, path: 'empresas', except: [:show, :update, :destroy] do
      collection do
        get 'new/:nif' => 'companies#nif_lookup', as: :nif_lookup
      end
    end
  end
  resources :companies, path: 'empresa', only: [:show, :update, :destroy]
  resources :markets, param: :market_id, path: 'feira', only: [:show, :update, :destroy] do
    member do
      get 'empresa/:id' => 'companies#show', as: :company
    end
  end
  resources :job_offers, path: '/oferta', only: [:new] do
    collection do
      get 'estudantes/:random_id' => 'job_offers#students', as: :students
    end
  end

  # devise_for :users
  get 'users/codes' => "users#random_index"
  devise_for :users, path: '', path_names: { sign_in: 'entrar', sign_out: 'sair'}
  resources :users do
    collection do
      resources :profiles
    end
  end
  match 'admin' => 'degrees#index', via: :get

  patch 'toggle_review/:id' => 'profiles#toggle_review', as: :profile_review
  patch 'profiles/:id/incomplete' => 'profiles#incomplete_profile', as: :incomplete_profile
  delete 'delete_curriculum/:id' => 'profiles#delete_curriculum', as: :delete_curriculum

  match 'perfil' => 'profiles#show', as: :my_profile, via: :get
  match 'perfil/editar' => 'profiles#edit', as: :edit_my_profile, via: :get
  match 'utilizador' => 'users#show', as: :my, via: :get
  get 'utilizador/qr' => 'users#qr_code', as: :my_qr

  get 'feira' => 'pages#market', as: :market_page
  scope 'feira', as: 'market' do
    resources :companies, only: [:show], path: :empresa do
      member do
        get 'qr' => "companies#company_qr", as: :qr
      end
    end
  end
  root 'pages#index'
end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
  include ActiveModel::Dirty

  has_many :applications, dependent: :destroy
  has_many :views, foreign_key: :job_offer_id, class_name: "JobView", dependent: :destroy
  has_and_belongs_to_many :programmes

  has_attached_file :image, styles: { medium: "300x300>" }, default_url: "/images/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validate :expires_at_validation
  validates_presence_of :company,
    :position,
    :location,
    :expires_at,
    :type_of_contract,
    :contract_duration,
    :description,
    :name,
    :email,
    :phone

  has_many :users, through: :applications

  before_create :generate_random_id

  after_create :mail_new_job_offer

  before_validation on: [:create] do
    self.expires_at ||= Date.today
  end

  after_save :mail_approved

  def send_applications
    self.applications_sent = true
    if self.save
      JobOfferMailer.job_offer_expired(self).deliver_later
      return true
    end
    return false
  end

  def restore
    self.trashed = false
    self.save
  end

  def trash
    self.trashed = true
    if self.save
      unless self.expired?
        JobOfferMailer.job_offer_reproved(self).deliver_later
      end
      return true
    end
    return false
  end

  def approve
    self.approved = true
    if self.save
      JobOfferMailer.job_offer_approved(self).deliver_later
    end
  end

  def mail_approved
    if saved_change_to_approved? and approved == true
      JobOfferMailer.job_offer_approved(self).deliver_later
    end
  end

  def mail_new_job_offer
    JobOfferMailer.new_job_offer(self).deliver_later
  end

  def mail_link
    JobOfferMailer.applications_link(self).deliver_later
  end

  def expired?
    Date.today > expires_at
  end

  def expires_at_validation
    if expires_at > JobOffer.max_expiration_date
      errors.add(:expires_at, "máximo de 3 meses")
    end
  end

  def generate_random_id
    while(!JobOffer.find_by(random_id: (self.random_id = SecureRandom.hex)).blank?)
    end
  end

  def self.max_expiration_date
    Date.today + 3.months
  end

  def self.locations
    [
      'Aveiro',
      'Beja',
      'Braga',
      'Bragança',
      'Castelo Branco',
      'Coimbra',
      'Évora',
      'Faro',
      'Guarda',
      'Leiria',
      'Lisboa',
      'Portalegre',
      'Porto',
      'Santarém',
      'Setúbal',
      'Viana do Castelo',
      'Vila Real',
      'Viseu',
      'Madeira',
      'Açores'
    ]
  end

  def self.types_of_contract
    ['Efetivo', 'Estágio', 'Part-time', 'Outro']
  end

  def update_view_count
    self.view_count = self.views.count
    self.save
  end

  def update_applications_number
    self.number_of_applications = self.applications.count
    self.save
  end
end

app/controllers/job_offers_controller.rb
class JobOffersController < ApplicationController
  before_action :set_job_offer, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource except: [:students]
  layout 'admin'

  # GET /job_offers
  # GET /job_offers.json
  def index
    if can? :manage, JobOffer
      if params[:expired]
        @filter = 'Expirado'
        @job_offers = JobOffer.where(trashed: false, approved: true, expires_at: (Date.today - 1.year)..(Date.today - 1.day)).order(approved: :asc, expires_at: :asc)
      elsif params[:approved]
        @filter = 'Aprovado'
        @job_offers = JobOffer.where(trashed: false, approved: true, expires_at: (Date.today)..(Date.today + 1.year)).order(expires_at: :asc)
      elsif params[:trashed]
        @filter = 'Eliminados'
        @job_offers = JobOffer.where(trashed: true).order(expires_at: :asc)
      elsif params[:all]
        @filter = 'Todos'
        @job_offers = JobOffer.all.order(approved: :asc, expires_at: :asc)
      else
        params[:to_approve] = true
        @filter = 'Por Aprovar'
        @job_offers = JobOffer.where(trashed: false, approved: false).order(expires_at: :asc)
      end
      render :admin_index
    end
  end

  # GET /job_offers/1
  # GET /job_offers/1.json
  def show
    current_user.create_view @job_offer
  end

  # GET /job_offers/new
  def new
    @job_offer = JobOffer.new expires_at: 3.months.from_now
    render layout: 'application'
  end

  # GET /job_offers/1/edit
  def edit
  end

  # POST /job_offers
  # POST /job_offers.json
  def create
    @job_offer = JobOffer.new(job_offer_params)

    respond_to do |format|
      if @job_offer.save
        message = 'A proposta foi submetida com sucesso e aguarda aprovação. Mais informações foram enviadas para o seu email.' 
        if can? :read, @job_offer
          format.html { redirect_to @job_offer, notice: message }
        else
          format.html { redirect_to root_path, notice: message }
        end
        format.json { render :show, status: :created, location: @job_offer }
      else
        format.html { render :new, layout: 'application' }
        format.json { render json: @job_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_offers/1
  # PATCH/PUT /job_offers/1.json
  def update
    respond_to do |format|
      if @job_offer.update(job_offer_params)
        if job_offer_params[:applications_sent]
          JobOfferMailer.applications_link(@job_offer).deliver_later
        end
        format.html { redirect_to @job_offer, notice: 'Oferta de emprego atualizada' }
        format.json { render :show, status: :ok, location: @job_offer }
      else
        format.html { render :edit }
        format.json { render json: @job_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /job_offers/1/send_applications
  def send_applications
    if @job_offer.send_applications
      respond_to do |format|
        format.html { redirect_to job_offers_url, notice: 'Candidaturas enviadas' }
        format.json { head :no_content }
      end
    end
  end

  # PATCH /job_offers/1/approve
  def approve
    if @job_offer.approve
      respond_to do |format|
        format.html { redirect_to job_offers_url, notice: 'Oferta de emprego aprovada' }
        format.json { head :no_content }
      end
    end
  end

  # PATCH /job_offers/1/restore
  def restore
    if @job_offer.restore
      respond_to do |format|
        format.html { redirect_to job_offers_url, notice: 'Oferta de emprego restaurada' }
        format.json { head :no_content }
      end
    end
  end

  # PATCH /job_offers/1/trash
  def trash
    if @job_offer.trash
      respond_to do |format|
        format.html { redirect_to job_offers_url, notice: 'Oferta de emprego eliminada' }
        format.json { head :no_content }
      end
    end
  end

  # DELETE /job_offers/1
  # DELETE /job_offers/1.json
  def destroy
    @job_offer.destroy
    respond_to do |format|
      format.html { redirect_to job_offers_url, notice: 'Oferta de emprego eliminada' }
      format.json { head :no_content }
    end
  end

  def students
    @job_offer = JobOffer.find_by random_id: params[:random_id]
    @students = @job_offer.users.joins(:profile).order('profiles.name')
    render layout: 'clean'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_offer
      @job_offer = JobOffer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_offer_params
      params.require(:job_offer).permit(:applications_sent, :image, :approved, :company, :location, :minimum_requirements, :type_of_contract, :contract_duration, :name, :email, :phone, :start_time, :end_time, :expires_at, :description, :position, :salary, programme_ids: [])
    end

    def search_params
      search_params = params.permit(:programme, :approved, :location, :contract, :filter)
      search = {expires_at: Date.today..(Date.today + 3.months)}
      if search_params[:contract]
        search[:type_of_contract] = search_params[:contract]
      end
      if search_params[:programme]
        search['job_offers_programmes.programme_id'] = search_params[:programme]
      end
      if search_params[:location]
        search[:location] = search_params[:location]
      end
      if search_params[:filter] == 'applications'
        search[:number_of_applications] = 0
      elsif search_params[:filter] == 'expiring'
        search[:expires_at] = Date.today..(Date.today + 2.weeks)
      end
      search[:approved] = true
      search
    end

    def order_params
      order_param = params[:order]
      order = {}
      if order_param == 'applications'
        order = {number_of_applications: :desc}
      elsif order_param == 'views'
        order = {view_count: :desc}
      end
      if params[:filter] == 'expiring'
        order[:expires_at] = :asc
      end
      order[:expires_at] = :asc
      #order[:updated_at] = :desc
      order
    end
end

app/helpers/job_offers_helper.rb
module JobOffersHelper
  def job_params
    params.permit(:job_id)
  end
end

app/views/job_offers/_form.html.erb
<%= form_for(job_offer) do |f| %>
  <% if job_offer.errors.any? %>
    <div id="error_explanation">
      <h5>Foram encontrados os seguintes erros:<% pluralize(job_offer.errors.count, "erro") %></h5>
      <ul>
      <% job_offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3>Empresa</h3>

  <div class="field">
    <%= f.label :image, 'Logo / Imagem' %>
    <%= f.file_field :image, as: :file %>
  </div>

  <div class="field">
    <%= f.label :company, class: "required" %>
    <%= f.text_field :company %>
  </div>

  <h3>Oferta</h3>

  <div class="field">
    <%= f.label :position, class: 'required' %>
    <%= f.text_field :position %>
  </div>

  <div class="field">
    <%= f.label :location, class: 'required' %>
    <%= f.select :location, JobOffer.locations, prompt: '(Selecionar)' %>
  </div>

  <div class="field-label">
    <%= f.label :expires_at, 'Prazo <small>oferta expira a</small>'.html_safe %>
  </div>
  <div class="job-time-field">
    <div class="field">
      <%= f.date_select(
        :expires_at,
        date_separator: '<div class="time-separator">:</div>',
        start_year: Date.today.year,
        end_year: 3.months.from_now.year
      )
      %>
    </div>
  </div>

  <h3>Requisitos</h3>

  <% Degree.order(:order).each do |degree| %>
    <% if degree.programmes.order(:name).length > 0 %>
      <h5><%= degree.name %></h5>
      <%= f.collection_check_boxes :programme_ids, degree.programmes.order(:name), :id, :name do |cb| %>
        <%= cb.label(class: 'form-checkbox') { cb.check_box + cb.text } %>
      <% end %>
    <% end %>
  <% end %>

  <div class="field">
    <%= f.label :minimum_requirements, 'Requisitos Minimos' %>
    <%= f.text_area :minimum_requirements, rows: 5 %>
  </div>

  <h3>Contrato</h3>

  <div class="field">
    <%= f.label :type_of_contract, class: 'required' %>
    <%= f.select :type_of_contract, JobOffer.types_of_contract, prompt: '(Selecionar)' %>
  </div>

  <div class="field">
    <%= f.label :contract_duration, class: 'required' %>
    <%= f.text_field :contract_duration %>
  </div>

  <span>Horário de Trabalho</span>
  <div class="job-time-field">
    <div class="field">
      <div class="field-label">
        <%= f.label :start_time, 'Das' %>
      </div>
      <%= f.time_select :start_time, time_separator: '<div class="time-separator">:</div>', minute_step: 15, prompt: true %>
    </div>

    <div class="field">
      <div class="field-label">
        <%= f.label :end_time, 'Às' %>
      </div>
      <%= f.time_select :end_time, time_separator: '<div class="time-separator">:</div>', minute_step: 15, prompt: true %>
    </div>
  </div>

  <div class="field">
    <%= f.label :salary, 'Remuneração (€)' %>
    <%= f.number_field :salary, step: 0.05 %>
  </div>

  <div class="field">
    <%= f.label :description, class: 'required' %>
    <%= f.text_area :description, rows: 10 %>
  </div>

  <h3>Contacto do(a) responsável</h3>

  <div class="field">
    <%= f.label :name, class: 'required' %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email, class: 'required' %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone, class: 'required' %>
    <%= f.text_field :phone %>
  </div>

  <div class="actions">
    <%= f.button 'Enviar', class: 'button' %>
  </div>
<% end %>

app/views/job_offers/admin_index.html.erb
<div class="menu">
  <%= active_link_to fa_icon('calendar-check-o lg fw', text: 'Por Aprovar'), JobOffer, active: {to_approve: true} %>
  <%= active_link_to fa_icon('calendar lg fw', text: 'Aprovados'), job_offers_path(approved: true), active: {approved: true} %>
  <%= active_link_to fa_icon('calendar-times-o lg fw', text: 'Expirados'), job_offers_path(expired: true), active: {expired: true} %>
  <%= active_link_to fa_icon('trash-o lg fw', text: 'Eliminados'), job_offers_path(trashed: true), active: {trashed: true} %>
</div>

<h1><%= title "Emprego / #{@filter}" %></h1>

<div class="col">
  <table>
    <thead>
      <tr>
        <th>Empresa</th>
        <th>Cargo</th>
        <th>Candidaturas</th>
        <th>Expira a</th>
      </tr>
    </thead>

    <tbody>
      <% @job_offers.each do |job_offer| %>
        <tr>
          <td><%= link_to job_offer.company, job_offer %></td>
          <td><%= job_offer.position %></td>
          <td><%= job_offer.number_of_applications %></td>
          <td><%= l job_offer.expires_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/job_offers/edit.html.erb
<div class='menu'>
  <%= link_to fa_icon('level-up lg fw', text: 'Oferta de emprego'), @job_offer, class: 'button' %>
</div>

<% title 'Editar Oferta de Emprego' %>

<%= render 'form', job_offer: @job_offer %>

app/views/job_offers/index.html.erb
<% title 'Ofertas de Estágio/Emprego' %>

<div class="job-filters">
  <% @filters.each do |param, value| %>
    <div class="job-filter">
      <%= link_to fa_icon("times", text: value), job_offers_path(search_params.except(param)) %>
    </div>
  <% end %>
</div>

<div class="job-content">
  <div class="jobs">
    <% @job_offers.each do |job_offer| %>
      <% application = current_user.applications.find_by(job_offer: job_offer) %>
      <%= link_to job_offer, class: 'job-link', data: {id: application.blank? ? 0 : application.id} do %>
        <div class="card job-offer">

          <div class="job-image">
            <%= image_tag job_offer.image.url(:medium) %>
          </div>

          <div class="content">
            <h3><%= job_offer.position %></h3>
            <h4>por <strong><%= job_offer.company %></strong></h4>
            <span>Localização: <strong><%= job_offer.location %></strong></span>
            <span>Contrato: <strong><%= job_offer.type_of_contract %></strong></span>
          </div>

          <div class='engagement'>
            <div class="stats">
              <%= fa_icon 'suitcase fw', text: job_offer.number_of_applications %>
              <%= fa_icon 'eye fw', text: job_offer.view_count %>
            </div>

            <% if application.blank? %>
              <div class="job-add-application">
                Candidatar
              </div>
            <% else %>
              <div class="job-remove-application">
                Submetida
              </div>
            <% end %>
          </div>

        </div>
      <% end %>
      <% unless application.blank? %>
        <%= link_to(
          'Remover Candidatura',
          application,
          class: 'button alert hide',
          method: :delete,
          id: "application#{application.id}",
          data: { confirm: 'Tem a certeza?' }
        )%>
      <% end %>
    <% end %>
    <div class="job-link placeholder"></div>
    <div class="job-link placeholder"></div>
    <div class="job-link placeholder"></div>
    <div class="job-link placeholder"></div>
  </div>

  <div id="jobmenu">
    <h4>Ordenar</h4>
    <ul class="menu vertical">
      <li><%= link_to fa_icon('eye fw', text: 'Mais Vistos'), job_offers_path(search_params(order: :views)), class: ('active' if params[:order].eql? 'views') %></li>
      <li><%= link_to fa_icon('star fw', text: 'Mais Procurados'),  job_offers_path(search_params(order: :applications)), class: ('active' if params[:order].eql? 'applications') %></li>
    </ul>

    <h4>Filtrar</h4>
    <ul class="menu vertical">
      <li><%= link_to fa_icon('clock-o fw', text: 'A Expirar'), job_offers_path(search_params(filter: :expiring)), class: ('active' if params[:filter].eql? 'expiring') %></li>
      <li><%= link_to fa_icon('briefcase fw', text: 'Sem Candidaturas'), job_offers_path(search_params(filter: :applications)), class: ('active' if params[:filter].eql? 'applications') %></li>
    </ul>
  </div>

</div>


<div class="job-offer-panel hide">
  <div class="card job-offer-show">
    <%= fa_icon('times-circle-o 3x', id: 'job-offer-close') %>
    <%= form_for Application.new do |f| %>
      <%= f.hidden_field :job_offer_id %>
      <div id='job-img-container'>
        <img id='job-img'></img>
      </div>
      <div class="content">
        <h1 id='job-position'></h1>
        <h2>por <strong id='job-company'></strong></h2>
        <p><strong>Localização:</strong> <span id='job-location'></span></p>
        <p><strong>Candidatura até:</strong> <span id='job-expires-at'></span></p>
        <h5>Requisitos</h5>
        <p id='job-requirements'></p>
        <p><strong>Requisitos Mínimos:</strong> <span id='job-minimum-requirements'></span></p>
        <p><strong>Tipo de Contrato:</strong> <span id='job-contract'></span></p>
        <p><strong>Tempo de Contrato:</strong> <span id='job-duration'></span></p>
        <p><strong>Horário de Trabalho: </strong>Das <span id='job-start'></span> às <span id='job-end'></span></p>
        <h5>Descrição</h5>
        <p id='job-description'></p>
        <h5>Salário: <strong id='job-salary'></strong></h5>
      </div>

      <div class="button-container">
        <%= f.button 'Candidatar', class: 'button' %>
        <%= link_to 'Remover Candidatura', '', class: 'button alert', method: :delete, id: 'job-offer-link' %>
      </div>
    <% end %>
  </div>
</div>

app/views/job_offers/new.html.erb
<% title 'Nova Oferta' %>

<div id='job-offer' class="col">
  <%= render 'form', job_offer: @job_offer %>
</div>

app/views/job_offers/show.html.erb
<div class='menu'>
  <% if @job_offer.trashed %>
    <%= link_to fa_icon('level-up lg fw', text: 'Ofertas de emprego'), job_offers_path(trashed: true) %>
  <% elsif !@job_offer.approved? %>
    <%= link_to fa_icon('level-up lg fw', text: 'Ofertas de emprego'), job_offers_path %>
  <% elsif @job_offer.expired? %>
    <%= link_to fa_icon('level-up lg fw', text: 'Ofertas de emprego'), job_offers_path(expired: true) %>
  <% else %>
    <%= link_to fa_icon('level-up lg fw', text: 'Ofertas de emprego'), job_offers_path(approved: true) %>
  <% end %>
</div>

<h4><%= title @job_offer.company %> <small>(<%= @job_offer.number_of_applications %>)</small></h4>
<p><%= image_tag @job_offer.image.url %></p>

<p>
  <strong>Empresa:</strong>
  <%= @job_offer.company %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @job_offer.position %>
</p>

<p>
  <strong>Localização:</strong>
  <%= @job_offer.location %>
</p>

<p>
  <strong>Prazo de Candidatura:</strong>
  <%= l @job_offer.expires_at %>
</p>

<h4>Requisitos</h4>

<p>
  <strong>Estudos Mínimos:</strong>
  <% degree = '' %>
  <% @job_offer.programmes.left_outer_joins(:degree).order("degrees.order", :name).each do |programme| %>
    <% if degree != programme.degree.name %>
      <% if degree != '' %></ul><% end %>
      <% degree = programme.degree.name %>
      <h6><%= degree %></h6>
      <ul>
    <% end %>
    <li><%= programme.name %></li>
  <% end %>
  </ul>
</p>

<p>
  <strong>Requisitos Mínimos:</strong>
  <%= @job_offer.minimum_requirements %>
</p>

<p>
  <strong>Tipo de Contrato:</strong>
  <%= @job_offer.type_of_contract %>
</p>

<p>
  <strong>Duração:</strong>
  <%= @job_offer.contract_duration %>
</p>

<p>
  <% if @job_offer.start_time and @job_offer.end_time %>
    <strong>Horário de Trabalho:</strong>
    Das <%= l @job_offer.start_time %>
    às <%= l @job_offer.end_time %>
  <% end %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= simple_format @job_offer.description %>
</p>

<p>
  <strong>Salário:</strong>
  <%= number_to_currency @job_offer.salary %>
</p>

<h4>Contacto</h4>

<p>
  <strong>Nome:</strong>
  <%= @job_offer.name %>
</p>

<p>
  <strong>email:</strong>
  <%= mail_to @job_offer.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @job_offer.phone %>
</p>

<%= form_for @job_offer, remote: true do |f| %>
  <div class='menu'>
    <%= link_to fa_icon('check fw', text: 'Aprovar'), approve_job_offer_path(@job_offer), method: :patch, class: 'button success' if (!@job_offer.approved and !@job_offer.trashed) %>
    <%= link_to fa_icon('check fw', text: 'Restaurar'), restore_job_offer_path(@job_offer), method: :patch, class: 'button' if @job_offer.trashed %>
    <%= link_to fa_icon('paper-plane fw', text: 'Enviar candidaturas'), send_applications_job_offer_path(@job_offer), class: "button#{@job_offer.applications_sent ? " success" : ""}", method: :patch if (@job_offer.expired? and !@job_offer.trashed) %>
    <%= link_to fa_icon('pencil fw', text: 'Editar'), edit_job_offer_path(@job_offer), class: "button" if (!@job_offer.expired? and !@job_offer.trashed) %>
    <%= link_to fa_icon('briefcase fw', text: 'Ver candidaturas'), students_job_offers_path(@job_offer.random_id), class: 'button', target: "_blank" if @job_offer.approved %>
    <%= link_to fa_icon('trash fw', text: 'Eliminar'), trash_job_offer_path(@job_offer), method: :patch, class: 'button alert', data: { confirm: 'Are you sure?' } if !@job_offer.trashed %>
    <%= link_to fa_icon('trash fw', text: 'Eliminar permanentemente'), @job_offer, method: :delete, class: 'button alert', data: { confirm: 'Are you sure?' } if @job_offer.trashed %>
  </div>
<% end %>

app/views/job_offers/students.html.erb
<div class="admin-content">
  <% if @job_offer.expired? or current_user.has_role? :admin or current_user.has_role? :blat %>
    <h1><%= title 'Candidaturas' %></h1>
    <% @students.each do |student| %>
      <div class="job-offer-student">
        <%= link_to(
          student.profile.curriculum.url,
          target: '_blank',
          download: true,
          data: {filename: "#{student.profile.programme.full_name} - #{student.name}.pdf"}
        ) do %>
          <div class="job-offer-student-name">
            <%= student.name %>
          </div>
          <div class="job-offer-student-programme">
            <%= student.profile.programme.full_name %>
          </div>
          <div class="job-offer-student-icon">
            <%= fa_icon('download') %>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="text-right">
      <% link_to(
        fa_icon('download', text: 'Transferir todos'),
        '',
        class: 'button',
        id: 'job-offer-download-all',
      ) %>
    </div>
    <hr>
  <% end %>

  <h1><%= @job_offer.company %></h1>
  <p><%= image_tag @job_offer.image.url %></p>

  <p>
    <strong>Cargo:</strong>
    <%= @job_offer.position %>
  </p>

  <p>
    <strong>Localização:</strong>
    <%= @job_offer.location %>
  </p>


  <p>
    <strong>Prazo de Candidatura:</strong>
    <%= l @job_offer.expires_at %>
  </p>

  <h4>Requisitos</h4>

  <p>
    <strong>Estudos Mínimos:</strong>
    <% degree = '' %>
    <% @job_offer.programmes.left_outer_joins(:degree).order("degrees.order", :name).each do |programme| %>
      <% if degree != programme.degree.name %>
        <% if degree != '' %></ul><% end %>
        <% degree = programme.degree.name %>
        <h6><%= degree %></h6>
        <ul>
      <% end %>
      <li><%= programme.name %></li>
    <% end %>
    </ul>
  </p>

  <p>
    <strong>Requisitos Mínimos:</strong>
    <%= @job_offer.minimum_requirements %>
  </p>

  <p>
    <strong>Tipo de Contrato:</strong>
    <%= @job_offer.type_of_contract %>
  </p>

  <p>
    <strong>Duração:</strong>
    <%= @job_offer.contract_duration %>
  </p>

  <p>
    <% if @job_offer.start_time and @job_offer.end_time %>
      <strong>Horário de Trabalho:</strong>
      Das <%= l @job_offer.start_time %>
      às <%= l @job_offer.end_time %>
    <% end %>
  </p>

  <p>
    <strong>Descrição:</strong>
    <%= simple_format @job_offer.description %>
  </p>

  <p>
    <strong>Salário:</strong>
    <%= number_to_currency @job_offer.salary %>
  </p>

  <h4>Contacto</h4>

  <p>
    <strong>Nome:</strong>
    <%= @job_offer.name %>
  </p>

  <p>
    <strong>email:</strong>
    <%= mail_to @job_offer.email %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= @job_offer.phone %>
  </p>
</div>